apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-tool
  labels:
    app: cloud-tool
spec:
  selector:
    matchLabels:
      app: cloud-tool
  replicas: 2
  template:
    metadata:
      labels:
        app: cloud-tool
    spec:
      containers:
        - name: cloud-tool
          image: cloud-tool:0.1.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "1"
              memory: 500Mi
            requests:
              cpu: 500m
              memory: 10Mi